const router=require('express').Router(); const {auth,roles}=require('../middleware/auth'); const {read,transact,now,id}=require('../db'); const {moderate}=require('../services/moderation');
const admin=[auth,roles('admin')]; async function audit(adminId,action,targetType,targetId,metadata={}){await transact(db=>db.auditLogs.push({id:id(),adminId,action,targetType,targetId,metadata,createdAt:now(),updatedAt:now()}))}
router.get('/users',...admin,(req,res)=>res.json({success:true,data:read().users.map(({passwordHash,...u})=>u)}));
router.put('/users/:id/block',...admin,async(req,res,next)=>{try{if(req.params.id===req.user.id)return res.status(400).json({success:false,message:'Admin cannot block self',error:'SELF_BLOCK'});await transact(db=>{const u=db.users.find(x=>x.id===req.params.id);if(u){u.status='blocked';u.updatedAt=now()}});await audit(req.user.id,'block_user','user',req.params.id);res.json({success:true,data:{blocked:true}})}catch(e){next(e)}});
router.put('/users/:id/unblock',...admin,async(req,res,next)=>{try{await transact(db=>{const u=db.users.find(x=>x.id===req.params.id);if(u){u.status='active';u.updatedAt=now()}});await audit(req.user.id,'unblock_user','user',req.params.id);res.json({success:true,data:{blocked:false}})}catch(e){next(e)}});
router.get('/listings',...admin,(req,res)=>res.json({success:true,data:read().listings}));
router.post('/listings/:id/approve',...admin,async(req,res,next)=>{try{const x=read().listings.find(v=>v.id===req.params.id);if(!x)return res.status(404).json({success:false,message:'Not found',error:'NOT_FOUND'});const m=moderate(x.title,x.description,x.skills);if(m.blocked)return res.status(403).json({success:false,message:'Content is still prohibited',error:'MODERATION_BLOCKED'});await transact(db=>{const y=db.listings.find(v=>v.id===x.id);y.status='approved';y.moderationReason=null;y.updatedAt=now()});await audit(req.user.id,'approve_listing','listing',x.id);res.json({success:true,data:{approved:true}})}catch(e){next(e)}});
router.post('/listings/:id/reject',...admin,async(req,res,next)=>{try{await transact(db=>{const x=db.listings.find(v=>v.id===req.params.id);if(x){x.status='rejected';x.moderationReason=String(req.body?.reason||'Rejected by moderation').slice(0,500);x.updatedAt=now()}});await audit(req.user.id,'reject_listing','listing',req.params.id,{reason:req.body?.reason||''});res.json({success:true,data:{rejected:true}})}catch(e){next(e)}});
router.get('/categories',...admin,(req,res)=>res.json({success:true,data:read().categories})); router.get('/payments',...admin,(req,res)=>res.json({success:true,data:read().payments.map(p=>({...p,metadata:undefined}))}));
router.get('/audit-logs',...admin,(req,res)=>res.json({success:true,data:read().auditLogs})); router.get('/statistics',...admin,(req,res)=>{const d=read(),users=d.users;res.json({success:true,data:{totalUsers:users.length,seekers:users.filter(x=>x.role==='seeker').length,employers:users.filter(x=>x.role==='employer').length,admins:users.filter(x=>x.role==='admin').length,totalListings:d.listings.length,pendingListings:d.listings.filter(x=>x.status==='pending').length,approvedListings:d.listings.filter(x=>x.status==='approved').length,rejectedListings:d.listings.filter(x=>x.status==='rejected').length,applications:d.applications.length,premiumUsers:users.filter(x=>x.premium&&x.premiumExpiresAt&&new Date(x.premiumExpiresAt)>new Date()).length,totalPayments:d.payments.length,revenue:d.payments.filter(x=>x.status==='completed').reduce((s,x)=>s+Number(x.amount||0),0)}})}); module.exports=router;
